language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
 # Build/test dependencies
  #- pip3 install -r requirements.txt
  # Get fab to test fab
  - python setup.py install

